/**
 * Build-time generator for the US legality map geometry.
 *
 * Projects the us-atlas TopoJSON with d3-geo (geoAlbersUsa) into fixed SVG path
 * strings and writes them to src/components/tracker/usStatePaths.ts. Committing
 * the output keeps d3-geo/topojson-client/us-atlas as build-only deps — the
 * shipped site renders a plain inline <svg> with zero client-side map library.
 *
 * Run: node scripts/generate-us-map.mjs  (or `npm run map:generate`).
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { geoAlbersUsa, geoPath } from 'd3-geo';
import { feature } from 'topojson-client';
import usAtlas from 'us-atlas/states-10m.json' with { type: 'json' };

const FIPS_TO_CODE = {
  '01': 'AL', '02': 'AK', '04': 'AZ', '05': 'AR', '06': 'CA', '08': 'CO',
  '09': 'CT', '10': 'DE', '11': 'DC', '12': 'FL', '13': 'GA', '15': 'HI',
  '16': 'ID', '17': 'IL', '18': 'IN', '19': 'IA', '20': 'KS', '21': 'KY',
  '22': 'LA', '23': 'ME', '24': 'MD', '25': 'MA', '26': 'MI', '27': 'MN',
  '28': 'MS', '29': 'MO', '30': 'MT', '31': 'NE', '32': 'NV', '33': 'NH',
  '34': 'NJ', '35': 'NM', '36': 'NY', '37': 'NC', '38': 'ND', '39': 'OH',
  '40': 'OK', '41': 'OR', '42': 'PA', '44': 'RI', '45': 'SC', '46': 'SD',
  '47': 'TN', '48': 'TX', '49': 'UT', '50': 'VT', '51': 'VA', '53': 'WA',
  '54': 'WV', '55': 'WI', '56': 'WY',
};

const __dirname = dirname(fileURLToPath(import.meta.url));
const projection = geoAlbersUsa().scale(1300).translate([487.5, 305]);
const path = geoPath(projection);
const geo = feature(usAtlas, usAtlas.objects.states);

/** Trim SVG path coordinate precision to 1 decimal to shrink the inlined map. */
function roundPath(d) {
  return d.replace(/-?\d+\.\d+/g, (n) => String(Math.round(parseFloat(n) * 10) / 10));
}

const paths = {};
for (const shape of geo.features) {
  const fips = String(shape.id).padStart(2, '0');
  const code = FIPS_TO_CODE[fips];
  if (!code) continue;
  const raw = path(shape);
  if (!raw) continue;
  const d = roundPath(raw);
  // Also compute a label centroid for optional postal-code overlays.
  const [cx, cy] = path.centroid(shape);
  paths[code] = { d, cx: Math.round(cx), cy: Math.round(cy) };
}

const out = `/**
 * AUTO-GENERATED by scripts/generate-us-map.mjs — do not edit by hand.
 * geoAlbersUsa projection, viewBox 0 0 975 610. Keyed by 2-letter state code.
 */
export type StatePathGeometry = { d: string; cx: number; cy: number };

export const US_STATE_PATHS: Record<string, StatePathGeometry> = ${JSON.stringify(paths, null, 2)};
`;

const target = resolve(__dirname, '../src/components/tracker/usStatePaths.ts');
writeFileSync(target, out, 'utf8');
console.log(`Wrote ${Object.keys(paths).length} state paths to ${target}`);
